version: '3.7'
services:

  postgres:
    image: postgres:13.3-alpine
    container_name: postgres-local
    hostname: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_DB=notification-dev

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper-local
    hostname: zookeeper
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 2s
      timeout: 2s
      retries: 15
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-1-local
    hostname: kafka-1
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INTERNAL://kafka-1:29092, EXTERNAL://kafka-1:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092, EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-2:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-2-local
    hostname: kafka-2
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INTERNAL://kafka-2:29092, EXTERNAL://kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092, EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-3:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-3-local
    hostname: kafka-3
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INTERNAL://kafka-3:29092, EXTERNAL://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29092, EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    container_name: schema-registry-local
    hostname: schema-registry
    restart: always
    depends_on:
      - kafka-setup
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'kafka-1:29092'
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-setup:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
               cub kafka-ready -b kafka-1:29092 1 20 && \
               cub kafka-ready -b kafka-2:29092 1 20 && \
               cub kafka-ready -b kafka-3:29092 1 20 && \
               kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 3 --replication-factor 2 --topic notification-event && \
               kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 3 --replication-factor 2 --topic zipkin'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  kafka-ui:
    image: obsidiandynamics/kafdrop:3.27.0
    restart: on-failure
    container_name: kafka-ui-local
    hostname: kafka-ui
    depends_on:
      - schema-registry
    environment:
      KAFKA_BROKERCONNECT: kafka-1:29092, kafka-2:29092, kafka-3:29092
      SERVER_SERVLET_CONTEXTPATH: /
      SCHEMAREGISTRY_CONNECT: http://schema-registry:8081
      JVM_OPTS: "-Xms32M -Xmx64M"
    ports:
      - 9000:9000