server:
  port: 8082

spring:
  zipkin:
    kafka:
      topic: zipkin
    sender:
      type: KAFKA
  kafka:
    bootstrap-servers: http://localhost:9092, http://localhost:9093, http://localhost:9094
    listener:
      missing-topics-fatal: false
  thymeleaf:
    enabled: false
  cloud:
    config:
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
            allowedMethods:
              - POST
              - PUT
              - OPTIONS
      routes:
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/notifications/**
            - Header=X-CSRF-TOKEN, [0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}
            - Host=**localhost**
          filters:
            - name: NotificationPreFilter
            - name: NotificationPostFilter

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 1s
      cancelRunningFuture: false
  instances:
    notification-service:
      timeoutDuration: 250ms

logging:
  level:
    org.springframework: debug
    org.springframework.cloud: debug
    com.api.gateway.demo: debug

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      enabled: true
      uri: http://config-server-prod:8088
      fail-fast: true