# spring specific properties
spring:
  main:
    lazy-initialization: false
    web-application-type: servlet
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 60s
  jackson:
    time-zone: UTC
    locale: en_US
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/notifications?currentSchema"
    username: "user"
    password: "P@55w0rd"
    hikari:
      minimumIdle: 1
      maximumPoolSize: 3
      autoCommit: false
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        default_schema: "notification"
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: "jdbc:postgresql://localhost:5432/notification?currentSchema"
    username: "user"
    password: "P@55w0rd"
    default-schema: "notification"
  kafka:
    consumer:
      bootstrap-servers: http://localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: notification-events-listener-group
    template:
      default-topic: notification-event
    listener:
      ack-mode: manual

# server specific properties
server:
  port: 8081
  shutdown: graceful
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
    application-display-name: kafka-consumer
  compression:
    enabled: true
    min-response-size: 2KB # default value
    mime-types: "text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, image/jpeg, image/png, application/octet-stream"
  error:
    whitelabel:
      enabled: false

# log specific properties
logging:
  level:
    root: info
    org:
      springframework:
        boot: info
        kafka: info
