spring:
  application:
    name: producer-service
  config:
    activate:
      on-profile: default
    import: configserver:http://localhost:8088?fail-fast=true&max-attempts=3&max-interval=1500&multiplier=1.2&initial-interval=1100

server:
  port: 8083
  error:
    whitelabel:
      enabled: false