server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fragaLY/configs.git
          clone-on-start: true

logging:
  level:
    org.springframework: info
    org.springframework.cloud: info
    by.vk.configserver: info