server:
  port: 8088

spring:
  application:
    name: config-service
  main:
    banner-mode: off
  thymeleaf:
    enabled: false
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          force-pull: true

logging:
  level:
    org.springframework: info
    org.springframework.cloud: info
    by.vk.configserver: info