server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fragaLY/notification-configs.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          force-pull: true

logging:
  level:
    org.springframework: info
    org.springframework.cloud: info
    by.vk.configserver: info