version: '3.7'
services:

  config-server-prod:
    image: fragaly/config-server
    restart: on-failure

  postgres-prod:
    image: postgres:12.3
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_DB=notification-dev

  zookeeper-prod:
    image: confluentinc/cp-zookeeper:5.0.4
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-prod:
    image: confluentinc/cp-kafka:5.0.4
    depends_on:
      - zookeeper-prod
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-prod:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-prod:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  schema-registry-prod:
    image: confluentinc/cp-schema-registry:5.0.4
    restart: always
    depends_on:
      - kafka-prod
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-prod:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-prod
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry-prod:8081

  kafka-ui-prod:
    image: obsidiandynamics/kafdrop
    restart: on-failure
    depends_on:
      - schema-registry-prod
    environment:
      KAFKA_BROKERCONNECT: kafka-prod:9092
      SERVER_SERVLET_CONTEXTPATH: /
      SCHEMAREGISTRY_CONNECT: http://schema-registry-prod:8081
      JVM_OPTS: "-Xms32M -Xmx64M"
    ports:
      - 9000:9000

  gateway-prod:
    image: fragaly/gateway
    restart: on-failure
    depends_on:
      - config-server-prod

  producer-prod:
    image: fragaly/producer
    restart: on-failure
    depends_on:
      - schema-registry-prod
      - gateway-prod

  consumer-prod:
    image: fragaly/consumer
    restart: on-failure
    depends_on:
      - schema-registry-prod
      - gateway-prod

  web-prod:
    image: fragaly/web
    restart: on-failure
    ports:
      - 80:80