name: ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      #PREPARATION
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
          architecture: x64
      - name: GRADLE PREPARATION
        run: chmod +x gradlew
      #FRONTEND
      script:
        - cd ~/notification-app
      - name: NPM INSTALLATION
        run: npm install --only=prod --silent
      - name: NPM BUILDING
        run: npm run build
      - name: FRONTEND DOCKER IMAGE DELIVERY
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: integr8ed/inad-client
          tags: 1.0.0, latest
      #PRODUCER
      script:
        - cd ~/kafka-producer
      - name: PRODUCER COMPILATION
        run: ./gradlew compileKotlin -x compileJava --parallel
      - name: PRODUCER TESTS
        run: ./gradlew test -x compileTestJava --parallel
      - name: PRODUCER BUILD
        run: ./gradlew build -x test -x compileJava --parallel
      - name: PRODUCER DOCKER DELIVERY
        if: github.ref == 'refs/heads/master'
        run: ./gradlew jib
      #CONSUMER
      script:
        - cd ~/kafka-producer
      - name: CONSUMER COMPILATION
        run: ./gradlew compileKotlin -x compileJava --parallel
      - name: CONSUMER TESTS
        run: ./gradlew test -x compileTestJava --parallel
      - name: CONSUMER BUILD
        run: ./gradlew build -x test -x compileJava --parallel
      - name: CONSUMER DOCKER DELIVERY
        if: github.ref == 'refs/heads/master'
        run: ./gradlew jib