name: ci/cd

on:
  push:
    branches:
      - master

jobs:
  producer:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: kafka-producer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          architecture: x64
      - name: GRADLE PREPARATION
        run: chmod +x gradlew
      - name: PRODUCER COMPILATION
        run: ./gradlew compileKotlin -x compileJava --parallel
      - name: PRODUCER TESTS
        run: ./gradlew test -x compileTestJava --parallel
      - name: PRODUCER BUILD
        run: ./gradlew build -x test -x compileJava --parallel
      - name: PRODUCER DOCKER DELIVERY
        if: github.ref == 'refs/heads/master'
        run: ./gradlew jib -Djib.to.image=${{ secrets.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/producer:latest -Djib.to.auth.username=${{ secrets.DOCKER_HUB_USER }} -Djib.to.auth.password=${{ secrets.DOCKER_HUB_PASSWORD }}
  consumer:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: kafka-consumer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          architecture: x64
      - name: GRADLE PREPARATION
        run: chmod +x gradlew
      - name: CONSUMER COMPILATION
        run: ./gradlew compileKotlin -x compileJava --parallel
      - name: CONSUMER TESTS
        run: ./gradlew test -x compileTestJava --parallel
      - name: CONSUMER BUILD
        run: ./gradlew build -x test -x compileJava --parallel
      - name: CONSUMER DOCKER DELIVERY
        if: github.ref == 'refs/heads/master'
        run: ./gradlew jib -Djib.to.image=${{ secrets.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/consumer:latest -Djib.to.auth.username=${{ secrets.DOCKER_HUB_USER }} -Djib.to.auth.password=${{ secrets.DOCKER_HUB_PASSWORD }}
  gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: gateway
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          architecture: x64
      - name: GRADLE PREPARATION
        run: chmod +x gradlew
      - name: GATEWAY COMPILATION
        run: ./gradlew compileKotlin -x compileJava --parallel
      - name: GATEWAY TESTS
        run: ./gradlew test -x compileTestJava --parallel
      - name: GATEWAY BUILD
        run: ./gradlew build -x test -x compileJava --parallel
      - name: GATEWAY DOCKER DELIVERY
        if: github.ref == 'refs/heads/master'
        run: ./gradlew jib -Djib.to.image=${{ secrets.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/gateway:latest -Djib.to.auth.username=${{ secrets.DOCKER_HUB_USER }} -Djib.to.auth.password=${{ secrets.DOCKER_HUB_PASSWORD }}
  config-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: config-server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          architecture: x64
      - name: GRADLE PREPARATION
        run: chmod +x gradlew
      - name: CONFIG SERVER COMPILATION
        run: ./gradlew compileKotlin -x compileJava --parallel
      - name: CONFIG SERVER BUILD
        run: ./gradlew build -x test -x compileJava --parallel
      - name: CONFIG SERVER DOCKER DELIVERY
        env:
          GIT_CONFIG_URL: https://github.com/fragaLY/notification-configs.git
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        if: github.ref == 'refs/heads/master'
        run: ./gradlew jib -Djib.to.image=${{ secrets.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/config-server:latest -Djib.to.auth.username=${{ secrets.DOCKER_HUB_USER }} -Djib.to.auth.password=${{ secrets.DOCKER_HUB_PASSWORD }}
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: notification-app
    steps:
      - name: FRONTEND CHECKOUT
        uses: actions/checkout@v2
      - name: FRONTEND DOCKER IMAGE DELIVERY
        uses: docker/build-push-action@v1
        with:
          dockerfile: notification-app/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: fragaly/web
          tags: latest